http_server:
  address: "localhost:8080"
  timeout: 30s
  iddle_timeout: 60s
  tls:
    certfile: "certs/server.crt"
    keyfile: "certs/server.key"

database:
  host: "localhost"
  port: "5432"
  databaseName: "postgres"
  user: "postgres"
  password: ""

valkey:
  host: "localhost"
  port: "6379"
  user: "default"
  password: ""